### ISSUE TITLE
Inaccurate lack of support reported in Chrome

### ISSUE THREAD

**Issue by alebelcor** [nucliweb/avif-in-css#3]
Hi,

It seems the `polyfill.js` file reports lack of support in Chrome which, as far as I'm aware, has support since version 85 as reported [here](https://caniuse.com/avif).

I tested with Chrome 92.

You can reproduce it here: https://codepen.io/alebelcor/full/bGWMVzO

Maybe I'm doing something wrong?

Thanks for reading!

**Comment by felixicaza** [comment]
Hi @alebelcor  (probably a late reply), but I recently discovered this little polyfill and have had exactly the same problem.

For some strange reason the problem has to do with the Base64 converted image with which the support is checked, I managed to fix it by replacing it with this one:

`data:image/avif;base64,AAAAIGZ0eXBhdmlmAAAAAGF2aWZtaWYxbWlhZk1BMUIAAADybWV0YQAAAAAAAAAoaGRscgAAAAAAAAAAcGljdAAAAAAAAAAAAAAAAGxpYmF2aWYAAAAADnBpdG0AAAAAAAEAAAAeaWxvYwAAAABEAAABAAEAAAABAAABGgAAAB0AAAAoaWluZgAAAAAAAQAAABppbmZlAgAAAAABAABhdjAxQ29sb3IAAAAAamlwcnAAAABLaXBjbwAAABRpc3BlAAAAAAAAAAIAAAACAAAAEHBpeGkAAAAAAwgICAAAAAxhdjFDgQ0MAAAAABNjb2xybmNseAACAAIAAYAAAAAXaXBtYQAAAAAAAAABAAEEAQKDBAAAACVtZGF0EgAKCBgANogQEAwgMg8f8D///8WfhwB8+ErK42A=`

**Comment by nucliweb** [comment]
Thanks a lot @Felix-Icaza 😊

**Comment by felixicaza** [comment]
@nucliweb Amazing! thanks for this polyfill :100:
