### ISSUE TITLE
PostCSS version is too strict

### ISSUE THREAD

**Issue by romainmenke** [nucliweb/avif-in-css#6]
https://github.com/nucliweb/avif-in-css/blob/bf4ca1312091445a532cfe00a709ec0633481aac/package.json#L45

Would be better as `"postcss": "^8.1.14"`

**Comment by nucliweb** [comment]
Fixed [here](https://github.com/nucliweb/avif-in-css/commit/dffbf533291743e130d91222796f536ca5586d43), thanks
